Repository jmprathab/MyHome, pull requests merged in 2020-10, with the labels that each got.

#144 Issue 111: Endpoint for updating an amenity
  src/main/java/com/myhome/controllers/AmenityController.java
  src/main/java/com/myhome/controllers/dto/CommunityAmenityDto.java
  src/main/java/com/myhome/controllers/mapper/AmenityApiMapper.java
  src/main/java/com/myhome/controllers/mapper/SchedulePaymentApiMapper.java
  src/main/java/com/myhome/controllers/request/UpdateAmenityRequest.java
  src/main/java/com/myhome/domain/Amenity.java
  src/main/java/com/myhome/domain/BaseEntity.java
  src/main/java/com/myhome/services/AmenityService.java
  src/main/java/com/myhome/services/springdatajpa/AmenitySDJpaService.java
  src/main/java/com/myhome/services/springdatajpa/PaymentSDJpaService.java
  src/test/java/com/myhome/controllers/unit/AmenityControllerTest.java
  src/test/java/com/myhome/services/unit/AmenitySDJpaServiceTest.java
  src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
Labels: enhancement

#154 Issue #149 : Add current user as Admin when creating a community
  service/src/main/java/com/myhome/services/springdatajpa/CommunitySDJpaService.java
  service/src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
Labels: bug

#163 Issue #158: DataLoader class does nothing
  service/src/main/java/com/myhome/bootstrap/DataLoader.java
  service/src/main/java/com/myhome/bootstrap/TestDataConstants.java
Labels: enhancement

#177 Issue #168: Add info about code style to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#171 Issue #170: Users controller OpenApi migration
  api/build.gradle
  api/src/main/resources/api.yaml
  gradle.properties
  service/src/main/java/com/myhome/controllers/UserController.java
  service/src/main/java/com/myhome/controllers/mapper/UserApiMapper.java
  service/src/main/java/com/myhome/controllers/request/CreateUserRequest.java
  service/src/main/java/com/myhome/controllers/response/CreateUserResponse.java
  service/src/main/java/com/myhome/controllers/response/GetUserDetailsResponse.java
  service/src/test/java/com/myhome/controllers/integration/ControllerIntegrationTest.java
  service/src/test/java/com/myhome/controllers/integration/HouseMemberDocumentServiceIntegrationTest.java
  service/src/test/java/com/myhome/controllers/unit/UserControllerTest.java
Labels: awaiting-review, enhancement, hacktoberfest-accepted

#167 Issue #157: Repeating helper methods in tests
  service/src/main/java/com/myhome/domain/CommunityHouse.java
  service/src/test/java/com/myhome/controllers/HouseControllerTest.java
  service/src/test/java/com/myhome/services/unit/AmenitySDJpaServiceTest.java
  service/src/test/java/com/myhome/services/unit/CommunitySDJpaServiceTest.java
  service/src/test/java/com/myhome/services/unit/HouseMemberDocumentServiceTest.java
  service/src/test/java/com/myhome/services/unit/HouseSDJpaServiceTest.java
  service/src/test/java/com/myhome/services/unit/UserSDJpaServiceTest.java
  service/src/test/java/helpers/TestUtils.java
  tq
Labels: enhancement, hacktoberfest-accepted

#188 Issue #173: Migration of HouseMemberDocumentController to OpenApi yaml schema
  api/src/main/resources/api.yaml
  service/src/main/java/com/myhome/controllers/HouseMemberDocumentController.java
  service/src/test/java/com/myhome/controllers/HouseMemberDocumentTest.java
Labels: enhancement, hacktoberfest-accepted

#165 Issue #152: Add authorization filter for community
  service/src/main/java/com/myhome/security/WebSecurity.java
  service/src/main/java/com/myhome/security/filters/CommunityAuthorizationFilter.java
Labels: awaiting-review-changes, enhancement, hacktoberfest-accepted

#191 Issue #172: Migration of PaymentController to OpenApi yaml schema
  api/build.gradle
  api/src/main/resources/api.yaml
  service/src/main/java/com/myhome/controllers/CommunityController.java
  service/src/main/java/com/myhome/controllers/HouseMemberDocumentController.java
  service/src/main/java/com/myhome/controllers/PaymentController.java
  service/src/main/java/com/myhome/controllers/mapper/SchedulePaymentApiMapper.java
  service/src/main/java/com/myhome/controllers/request/EnrichedSchedulePaymentRequest.java
  service/src/main/java/com/myhome/controllers/request/SchedulePaymentRequest.java
  service/src/main/java/com/myhome/controllers/response/ListAdminPaymentsResponse.java
  service/src/main/java/com/myhome/controllers/response/ListMemberPaymentsResponse.java
  service/src/test/java/com/myhome/controllers/CommunityControllerTest.java
  service/src/test/java/com/myhome/controllers/HouseMemberDocumentTest.java
  service/src/test/java/com/myhome/controllers/PaymentControllerTest.java
Labels: enhancement, hacktoberfest-accepted

#203 Issue #183: Setup integration-tests module
  integration-tests/build.gradle
  integration-tests/src/test/java/com/myhome/controllers/UserControllerIntegrationTest.java
  service/build.gradle
Labels: awaiting-review-changes
